logging:
    file:
        name: consumer.log
    level:
        com:
            application:
                consumer: debug
management:
    endpoints:
        web:
            exposure:
                include: health
server:
    port: 8090

spring:
    kafka:
        consumer:
            properties:
                spring:
                    json:
                        trusted:
                            packages: "*"
#            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        bootstrap-servers: kafka:9092
